name: CI
on:
  push:
    branches: [main]
jobs:
  gitPull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script: |
            cd var/www/html/bebek
            git checkout .
            git pull
            npm install
            npm run start
            pm2 restart server.js
